// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl9lgzt8VMlP1RcgkdWcI3JhQb81IWi10',
    appId: '1:430887481580:web:5205da763fe211da0975c9',
    messagingSenderId: '430887481580',
    projectId: 'authenticator-97fc6',
    authDomain: 'authenticator-97fc6.firebaseapp.com',
    storageBucket: 'authenticator-97fc6.appspot.com',
    measurementId: 'G-6B1336HTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8VciKtqDyGitnCgGeoYHiGu6NayR81g',
    appId: '1:430887481580:android:e556e4058e8287640975c9',
    messagingSenderId: '430887481580',
    projectId: 'authenticator-97fc6',
    storageBucket: 'authenticator-97fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUykdWvlY69c8lHWPsfRQgidJb4t7tOo',
    appId: '1:430887481580:ios:a6633b69f638ea110975c9',
    messagingSenderId: '430887481580',
    projectId: 'authenticator-97fc6',
    storageBucket: 'authenticator-97fc6.appspot.com',
    iosClientId: '430887481580-s6bd2lu87r4iu0ngapl5ntmrv242crne.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLUykdWvlY69c8lHWPsfRQgidJb4t7tOo',
    appId: '1:430887481580:ios:f5b917644cde5ec90975c9',
    messagingSenderId: '430887481580',
    projectId: 'authenticator-97fc6',
    storageBucket: 'authenticator-97fc6.appspot.com',
    iosClientId: '430887481580-s74mpkm5vko8jaakq4oi7djj62guceha.apps.googleusercontent.com',
    iosBundleId: 'com.example.petsApp.RunnerTests',
  );
}
